package utils;

public class UserEmail {
	public static String userEmail(String ukey,String upass) {
		return "<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"UTF-8\">\r\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "    <link rel=\"stylesheet\" href=\"bootstrap.css\">\r\n"
				+ "    <link rel=\"stylesheet\" href=\"font-awesome.css\">\r\n"
				+ "    <title>Document</title>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "    <div class=\"container my-3 \" style=\"height: 100%;\">\r\n"
				+ "        <div class=\"row\">\r\n"
				+ "            <div class=\"col-md-8 offset-2 bg-light font-weight-normal\">\r\n"
				+ "                Dear Student,<br>\r\n"
				+ "                You Have been invited to take the Online assessment on 18 April by Deepak Rajput.<br><br>\r\n"
				+ "               \r\n"
				+ "                <h3>Test Credentials </h3>\r\n"
				+ "                <h4>User key : "+ukey+"</h4>\r\n"
				+ "                <h4>User password : "+upass+"</h4>\r\n"
				+ "\r\n"
				+ "                <table class=\"table\" >\r\n"
				+ "                    <thead class=\"\">\r\n"
				+ "                       <tr>\r\n"
				+ "                        <th>S.NO</th>\r\n"
				+ "                        <th>Subject</th>\r\n"
				+ "                        <th>Exam Date</th>\r\n"
				+ "                        <th>Exam Time</th>\r\n"
				+ "                       </tr>\r\n"
				+ "                    </thead>\r\n"
				+ "                    <tbody>\r\n"
				+ "                        <tr>\r\n"
				+ "                            <td>1</td>\r\n"
				+ "                            <td>Aptitude</td>\r\n"
				+ "                            <td>18 April</td>\r\n"
				+ "                            <td>2:00pm to 5:00pm</td>\r\n"
				+ "                        </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                </table><br>\r\n"
				+ "                <div class=\"text-center\">\r\n"
				+ "                    <input type=\"button\" name=\"btn\" value=\"Start Test\"><br><br>\r\n"
				+ "                    The test button will be active till 30 mins after the start time.<br><br>\r\n"
				+ "                </div>\r\n"
				+ "               \r\n"
				+ "                <h3>Important :</h3><br>\r\n"
				+ "			<ul>\r\n"
				+ "			<li>You can take this test anytime between the start date/time and end date/time.\r\n"
				+ "			<li>Once the test starts you cannot pause it. The test will run continuously for (duration). \r\n"
				+ "			Before you begin :\r\n"
				+ "\r\n"
				+ "			<br><br>\r\n"
				+ "\r\n"
				+ "				You are advised to go through the instructions below before taking the online test :\r\n"
				+ "			Instructions :\r\n"
				+ "			<li>You need to begin the test within the specified time interval.\r\n"
				+ "			<li>To take the test click on the provided test link or type the URL in the address bar of the Web Browser.\r\n"
				+ "			<li>Enter your one time key and password to get to the exam window.\r\n"
				+ "			<li>Fill the registration form with your details carefully.\r\n"
				+ "			<li>Read all the instruction and check all the requirements for smooth and uninterrupted test.\r\n"
				+ "			<li>Complete the test in one go.\r\n"
				+ "			</ul>\r\n"
				+ "\r\n"
				+ "               <h3>Hardware and Internet requirements:</h3><br>\r\n"
				+ "               <ul class=\"font-weight-normal\">\r\n"
				+ "                <li>A Personal Computer / Laptop. Please don�t take the test from Mobile Browser.\r\n"
				+ "                <li>A Webcam connected with the System/In-built Webcam in a laptop.\r\n"
				+ "                <li>Smooth and uninterrupted Internet connectivity (throughout the testing session), minimum 1 MBPS/4G.\r\n"
				+ "                        <br>\r\n"
				+ "                    <br><br>\r\n"
				+ "               </ul>\r\n"
				+ "               <h3>Browser/OS Requirements:<h3><br>\r\n"
				+ "               <ul class=\"font-weight-normal small\">\r\n"
				+ "                <li>This Assessment is supported by the below-listed Browsers/Versions only.\r\n"
				+ "                    <li>Google Chrome (version 40 and above)\r\n"
				+ "                      <li>Mozilla Firefox (version 40 and above)\r\n"
				+ "                      <li>In case you're taking the test on Windows 8, make sure you use the latest version and disable all the popups/ notifications.\r\n"
				+ "                              \r\n"
				+ "               </ul>\r\n"
				+ "\r\n"
				+ "                <br><br>\r\n"
				+ "               <h5>All the best!</h5>\r\n"
				+ "                <h5>Regards,</h5>\r\n"
				+ "                <h5>Online Test System</h5>\r\n"
				+ "            </div>\r\n"
				+ "        </div>\r\n"
				+ "    </div>\r\n"
				+ "</body>\r\n"
				+ "</html>";
	}
}
